language: node_js
node_js:
  - "0.8"
env:
  - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
before_install:
  - npm install -g grunt-cli
  - "echo 'Installing Casper'"
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.1-beta3
  - export PATH=$PATH:`pwd`/bin
  - cd -
before_script:
  - "export DISPLAY=:99.0"
  - phantomjs --version
  - casperjs --version
  - "sh -e /etc/init.d/xvfb start"
  - "echo 'Installing Slimer'"
  - "wget http://download.slimerjs.org/v0.9/0.9.0/slimerjs-0.9.0.zip"
  - "unzip slimerjs-0.9.0.zip"
  - "mv slimerjs-0.9.0 ./slimerjs"
  - slimerjs --version
addons:
  firefox: "25.0"