language: node_js
node_js:
  - "0.8"
before_install:
  - npm install -g grunt-cli
  - "echo 'Installing Casper'"
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - git checkout tags/1.1-beta3
  - export PATH=$PATH:`pwd`/bin
  - cd -
  - phantomjs --version
  - casperjs --version